# Generated by Django for selftest app

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('severity_scale', models.CharField(default='1-4', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Symptom',
                'verbose_name_plural': 'Symptoms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SelfTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('urgent', 'Urgent - Seek Immediate Care')], max_length=20)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('predicted_diseases', models.JSONField(blank=True, default=list)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_tests', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Self Test',
                'verbose_name_plural': 'Self Tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SymptomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField(choices=[(1, 'Mild'), (2, 'Moderate'), (3, 'Severe'), (4, 'Very Severe')])),
                ('duration_days', models.IntegerField(help_text='How many days have you had this symptom?')),
                ('notes', models.TextField(blank=True, help_text='Additional details about this symptom')),
                ('self_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_reports', to='selftest.selftest')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selftest.symptom')),
            ],
            options={
                'verbose_name': 'Symptom Report',
                'verbose_name_plural': 'Symptom Reports',
            },
        ),
        migrations.AddField(
            model_name='selftest',
            name='symptoms',
            field=models.ManyToManyField(through='selftest.SymptomReport', to='selftest.symptom'),
        ),
        migrations.AlterUniqueTogether(
            name='symptomreport',
            unique_together={('self_test', 'symptom')},
        ),
    ] 